apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quotes-k8s
  labels:
    app: hello-quotes-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-quotes-k8s
  template:
    metadata:
      labels:
        app: hello-quotes-k8s
    spec:
      containers:
        - name: hello-quotes-k8s
          image: 783623/kodilla-quotes:2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3